require_relative "test_helper"

module SymmetricEncryption
  class ConfigTest < Minitest::Test
    describe SymmetricEncryption::Config do
      let :the_test_path do
        "tmp/config_test"
      end

      let :the_config_file_name do
        File.join(File.dirname(__FILE__), "config", "symmetric-encryption.yml")
      end

      before do
        FileUtils.rm_rf(the_test_path)
        FileUtils.makedirs(the_test_path)
      end

      after do
        FileUtils.rm_rf(the_test_path)
      end

      def migrate(config)
        SymmetricEncryption::Config.send(:migrate_old_formats!, config)
      end

      describe ".read_file" do
        it "reads every environment with symbolized keys" do
          config = SymmetricEncryption::Config.read_file(the_config_file_name)

          assert_equal %i[test], config.keys
          assert ciphers = config[:test][:ciphers]
          assert_equal 2, ciphers.first[:version]
          assert_equal "aes-128-cbc", ciphers.first[:cipher_name]
        end

        it "evaluates ERB" do
          file_name = "#{the_test_path}/erb.yml"
          File.write(file_name, <<~CONFIG)
            production:
              ciphers:
                - key: <%= "A" * 32 %>
                  iv: <%= "B" * 16 %>
                  cipher_name: aes-256-cbc
                  version: 1
          CONFIG

          config = SymmetricEncryption::Config.read_file(file_name)
          assert_equal "A" * 32, config[:production][:ciphers].first[:key]
        end
      end

      describe ".write_file" do
        let :file_name do
          "#{the_test_path}/symmetric-encryption.yml"
        end

        let :config do
          {
            production: {
              ciphers: [
                {key: "A" * 32, iv: "B" * 16, cipher_name: "aes-256-cbc", version: 3, always_add_header: true}
              ]
            }
          }
        end

        it "adds the generated by header" do
          SymmetricEncryption::Config.write_file(file_name, config)

          assert_includes File.read(file_name), "# This file was auto generated by symmetric-encryption."
        end

        it "round trips through read_file" do
          SymmetricEncryption::Config.write_file(file_name, config)

          assert_equal config, SymmetricEncryption::Config.read_file(file_name)
        end

        it "creates the directory when it does not exist" do
          nested = "#{the_test_path}/a/b/symmetric-encryption.yml"
          SymmetricEncryption::Config.write_file(nested, config)

          assert File.exist?(nested)
        end

        it "writes string keys, not symbols" do
          SymmetricEncryption::Config.write_file(file_name, config)

          raw = YAML.safe_load_file(file_name, permitted_classes: [Symbol], aliases: true)
          assert_equal %w[production], raw.keys
          assert_equal %w[ciphers], raw["production"].keys
        end
      end

      describe "#initialize" do
        it "raises when the config file cannot be found" do
          assert_raises(SymmetricEncryption::ConfigError) do
            SymmetricEncryption::Config.new(file_name: "#{the_test_path}/missing.yml", env: "test").config
          end
        end

        it "raises when the environment is not in the config file" do
          config = SymmetricEncryption::Config.new(file_name: the_config_file_name, env: "no_such_env")
          assert_raises(SymmetricEncryption::ConfigError) { config.config }
        end

        it "uses the SYMMETRIC_ENCRYPTION_CONFIG environment variable" do
          previous                              = ENV.fetch("SYMMETRIC_ENCRYPTION_CONFIG", nil)
          ENV["SYMMETRIC_ENCRYPTION_CONFIG"]    = the_config_file_name
          config                                = SymmetricEncryption::Config.new(env: "test")

          assert_equal File.expand_path(the_config_file_name), config.file_name
          assert_equal "test", config.env
        ensure
          previous ? ENV["SYMMETRIC_ENCRYPTION_CONFIG"] = previous : ENV.delete("SYMMETRIC_ENCRYPTION_CONFIG")
        end
      end

      describe "#ciphers" do
        it "builds a cipher for every entry" do
          config = SymmetricEncryption::Config.new(file_name: the_config_file_name, env: "test")

          ciphers = config.ciphers
          assert_equal 5, ciphers.size
          assert ciphers.all?(SymmetricEncryption::Cipher)
          assert_equal 2, ciphers.first.version
        end
      end

      describe ".load!" do
        it "sets the primary and secondary ciphers" do
          previous_cipher    = SymmetricEncryption.cipher
          previous_secondary = SymmetricEncryption.secondary_ciphers

          SymmetricEncryption::Config.load!(file_name: the_config_file_name, env: "test")

          assert_equal 2, SymmetricEncryption.cipher.version
          assert_equal 4, SymmetricEncryption.secondary_ciphers.size
        ensure
          SymmetricEncryption.cipher            = previous_cipher
          SymmetricEncryption.secondary_ciphers = previous_secondary
        end
      end

      describe "migrating old formats" do
        it "moves an inline cipher under ciphers" do
          config = migrate(key: "A" * 32, iv: "B" * 16, cipher_name: "aes-256-cbc")

          assert_equal 1, config[:ciphers].size
          assert_equal "A" * 32, config[:ciphers].first[:key]
        end

        it "renames the old :cipher option to :cipher_name" do
          config = migrate(ciphers: [{key: "A" * 32, iv: "B" * 16, cipher: "aes-256-cbc"}])

          cipher = config[:ciphers].first
          assert_equal "aes-256-cbc", cipher[:cipher_name]
          refute cipher.key?(:cipher)
        end

        it "copies the top level private_rsa_key into every cipher" do
          config = migrate(
            private_rsa_key: "RSA KEY",
            ciphers:         [{encrypted_key: "1"}, {encrypted_key: "2"}]
          )

          refute config.key?(:private_rsa_key)
          assert(config[:ciphers].all? { |cipher| cipher[:private_rsa_key] == "RSA KEY" })
        end

        it "converts a string key_encrypting_key into private_rsa_key" do
          config = migrate(ciphers: [{encrypted_key: "1", key_encrypting_key: "RSA KEY"}])

          cipher = config[:ciphers].first
          assert_equal "RSA KEY", cipher[:private_rsa_key]
          refute cipher.key?(:key_encrypting_key)
        end

        it "leaves a nested key_encrypting_key alone" do
          config = migrate(ciphers: [{encrypted_key: "1", key_encrypting_key: {key: "A" * 32}}])

          cipher = config[:ciphers].first
          assert_equal({key: "A" * 32}, cipher[:key_encrypting_key])
          refute cipher.key?(:private_rsa_key)
        end

        it "warns when an encrypted key resolves to nil" do
          config = nil
          out, = capture_io { config = migrate(ciphers: [{encrypted_key: nil, iv: "B" * 16}]) }

          assert_includes out, "WARNING"
          assert_equal :placeholder, config[:ciphers].first[:key_env_var]
        end
      end
    end
  end
end
